module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'jest-environment-node',
  testMatch: ['**/__tests__/**/*.unit.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/index.ts',
    '!src/**/*.config.ts',
    '!src/**/config.ts',
    '!**/query-model.ts',
    '!**/mapper.ts',
    '!**/use-case.ts',
    '!**/*.repository.ts',
    '!**/*.fixture.ts',
    '!**/*.mock.ts',
    '!**/*.error.ts',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!src/**/*.enums.ts',
    '!src/**/*.errors.ts',
    '!src/**/*.error.ts',
    '!src/**/*.dtos.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.types.ts',
    '!src/**/*.type.ts',
    '!src/**/worker.ts',
    '!src/**/repository.ts',
    '!src/api/*',
  ],
};
